'use client';

import React, { useState } from 'react';

export function OtherProjects() {
  const [selectedProject, setSelectedProject] = useState<null | {
    title: string;
    subtitle: string;
    tech: string[];
    highlights: string[];
    github: string;
    problem: string;
    product: string;
    engineering: string[];
  }>(null);

  const projects = [
    {
      title: 'CivicFix',
      subtitle: 'Civic Issue Management & AI Duplicate Detection Platform',
      tech: ['Next.js', 'TypeScript', 'FastAPI', 'PostgreSQL', 'pgvector', 'HNSW'],
      highlights: [
        'Multi-role authentication for citizens and municipal administrators',
        'Civic issue reporting workflow with location tagging and image uploads',
        'AI duplicate issue detection powered by 384D vector embeddings',
        'High-performance vector search using pgvector with HNSW indexing',
      ],
      github: 'https://github.com/TejdeepNaik/CivicFix',
      problem: 'Municipal administrators receive thousands of overlapping civic complaints (e.g. potholes, streetlight failures), leading to duplicated effort and slow response times.',
      product: 'Citizens submit issue reports with geospatial data and photo attachments. Administrators view prioritized tickets, assign departments, and track resolution status.',
      engineering: [
        'Integrated FastAPI backend generating 384-dimensional text embeddings for incoming issue descriptions.',
        'Executed vector similarity queries in PostgreSQL using pgvector with HNSW indexing to flag near-duplicate issues automatically during report creation.',
        'Designed decoupled Next.js web application with role-based routing for citizen submission vs admin management.',
      ],
    },
    {
      title: 'CrowdInfra',
      subtitle: 'Civic Infrastructure Request & Analysis Platform',
      tech: ['Next.js', 'React', 'JavaScript', 'Google Maps API', 'Gemini AI', 'Vercel'],
      highlights: [
        'Infrastructure request submission and community voting workspace',
        'Google Maps & Google Places API integration for location tagging',
        'User authentication, ratings, and comment management',
        'Gemini AI automated infrastructure analysis and priority scoring',
      ],
      github: 'https://github.com/TejdeepNaik/CrowdInfra',
      problem: 'Local communities struggle to aggregate and prioritize regional infrastructure needs (roads, street lighting, public transit stops) for local council review.',
      product: 'An interactive web app where citizens drop map pins, detail infrastructure demands, upvote community proposals, and view automated priority scores generated by Gemini AI.',
      engineering: [
        'Embedded Google Maps API and Google Places SDK for precise location tagging and map rendering.',
        'Integrated Gemini AI prompt pipeline to evaluate issue severity based on description, location type, and community vote density.',
        'Built full-stack React / Next.js interface deployed on Vercel.',
      ],
    },
  ];

  return (
    <section id="projects" className="py-20 bg-[#090d16] border-b border-slate-800/80">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mb-12 flex flex-col sm:flex-row sm:items-end justify-between gap-4">
          <div>
            <h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight mb-2">
              Full-Stack &amp; AI Projects
            </h2>
            <p className="text-slate-400 text-sm sm:text-base">
              Targeted applications focusing on vector search, civic AI, geospatial integration, and web backends.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {projects.map((proj) => (
            <div
              key={proj.title}
              className="p-8 rounded-2xl bg-slate-900/80 border border-slate-800 hover:border-slate-700 transition flex flex-col justify-between"
            >
              <div>
                <div className="flex items-center justify-between mb-3">
                  <h3 className="text-2xl font-bold text-white">{proj.title}</h3>
                  <a
                    href={proj.github}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="p-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white transition"
                    aria-label={`View ${proj.title} on GitHub`}
                  >
                    <svg className="w-5 h-5 fill-current" viewBox="0 0 24 24">
                      <path fillRule="evenodd" clipRule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.53 1.032 1.53 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" />
                    </svg>
                  </a>
                </div>

                <p className="text-sm font-medium text-indigo-400 mb-4">{proj.subtitle}</p>

                <div className="flex flex-wrap gap-2 mb-6">
                  {proj.tech.map((t) => (
                    <span
                      key={t}
                      className="px-2.5 py-1 rounded bg-slate-950 text-slate-300 text-xs font-mono border border-slate-800"
                    >
                      {t}
                    </span>
                  ))}
                </div>

                <ul className="space-y-2 mb-6">
                  {proj.highlights.map((h, i) => (
                    <li key={i} className="flex items-start gap-2 text-xs sm:text-sm text-slate-300">
                      <span className="text-indigo-400 mt-1">•</span>
                      <span>{h}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <div className="flex items-center justify-between pt-4 border-t border-slate-800">
                <a
                  href={proj.github}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 text-xs font-semibold text-indigo-400 hover:text-indigo-300 transition"
                >
                  <span>GitHub Repository</span>
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14 5l7 7m0 0l-7 7m7-7H3" />
                  </svg>
                </a>

                <button
                  onClick={() => setSelectedProject(proj)}
                  className="text-xs font-semibold text-slate-400 hover:text-white transition underline underline-offset-4"
                >
                  View Details
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Detail Modal */}
      {selectedProject && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md">
          <div className="bg-[#0c1220] border border-slate-800 rounded-2xl max-w-2xl w-full max-h-[85vh] overflow-y-auto p-6 sm:p-8 shadow-2xl relative">
            <button
              onClick={() => setSelectedProject(null)}
              className="absolute top-4 right-4 p-2 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition"
              aria-label="Close modal"
            >
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>

            <h3 className="text-2xl font-bold text-white mb-1">{selectedProject.title}</h3>
            <p className="text-xs font-mono text-indigo-400 mb-6">{selectedProject.subtitle}</p>

            <div className="space-y-5 text-sm text-slate-300">
              <div>
                <h4 className="text-xs font-mono uppercase text-slate-400 font-bold mb-1">Problem</h4>
                <p className="leading-relaxed">{selectedProject.problem}</p>
              </div>

              <div>
                <h4 className="text-xs font-mono uppercase text-slate-400 font-bold mb-1">Product Capabilities</h4>
                <p className="leading-relaxed">{selectedProject.product}</p>
              </div>

              <div>
                <h4 className="text-xs font-mono uppercase text-slate-400 font-bold mb-2">Engineering &amp; Implementation Highlights</h4>
                <ul className="list-disc pl-5 space-y-1.5 text-slate-300 text-xs sm:text-sm">
                  {selectedProject.engineering.map((item, idx) => (
                    <li key={idx}>{item}</li>
                  ))}
                </ul>
              </div>

              <div className="pt-4 border-t border-slate-800 flex justify-between items-center">
                <a
                  href={selectedProject.github}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-5 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-xs transition"
                >
                  View GitHub Repository
                </a>

                <button
                  onClick={() => setSelectedProject(null)}
                  className="px-4 py-2 rounded-lg bg-slate-800 text-slate-300 hover:text-white text-xs font-medium"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </section>
  );
}
